//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkWorld.Prism.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinkWorld.Prism.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an address..
        /// </summary>
        public static string AddressError {
            get {
                return ResourceManager.GetString("AddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address....
        /// </summary>
        public static string AddressPlaceHolder {
            get {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL IN ONE.
        /// </summary>
        public static string AllInOne {
            get {
                return ResourceManager.GetString("AllInOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AlreadyAccount {
            get {
                return ResourceManager.GetString("AlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast cancer and the pandemic.
        /// </summary>
        public static string BrestCancerPandemic {
            get {
                return ResourceManager.GetString("BrestCancerPandemic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a city..
        /// </summary>
        public static string CityError {
            get {
                return ResourceManager.GetString("CityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your city....
        /// </summary>
        public static string CityPlaceHolder {
            get {
                return ResourceManager.GetString("CityPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the internet connection!.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a country..
        /// </summary>
        public static string CountryError {
            get {
                return ResourceManager.GetString("CountryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your country....
        /// </summary>
        public static string CountryPlaceHolder {
            get {
                return ResourceManager.GetString("CountryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account to start doing more.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create an account using social media.
        /// </summary>
        public static string CreateWithSocialMedia {
            get {
                return ResourceManager.GetString("CreateWithSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a department..
        /// </summary>
        public static string DepartmentError {
            get {
                return ResourceManager.GetString("DepartmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your department....
        /// </summary>
        public static string DepartmentPlaceHolder {
            get {
                return ResourceManager.GetString("DepartmentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disease affects 1 in 8 women according to a Globocan study..
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test collects cells with a fine needle, analyzes the results and generates a diagnosis..
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast cancer affects both men and women..
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pandemic one more obstacle.
        /// </summary>
        public static string Description4 {
            get {
                return ResourceManager.GetString("Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a document..
        /// </summary>
        public static string DocumentError {
            get {
                return ResourceManager.GetString("DocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your document number....
        /// </summary>
        public static string DocumentPlaceHolder {
            get {
                return ResourceManager.GetString("DocumentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email..
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email....
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User no found..
        /// </summary>
        public static string Error001 {
            get {
                return ResourceManager.GetString("Error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with that email is already registered..
        /// </summary>
        public static string Error002 {
            get {
                return ResourceManager.GetString("Error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City no found..
        /// </summary>
        public static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can all fight it.
        /// </summary>
        public static string FightIt {
            get {
                return ResourceManager.GetString("FightIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a first name..
        /// </summary>
        public static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name....
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Step.
        /// </summary>
        public static string FirstStep {
            get {
                return ResourceManager.GetString("FirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT PASSWORD?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Step.
        /// </summary>
        public static string FourStep {
            get {
                return ResourceManager.GetString("FourStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Camera.
        /// </summary>
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll send instructions on how to reset your password to the email address you have registered with us.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KNOW MORE.
        /// </summary>
        public static string KnowMore {
            get {
                return ResourceManager.GetString("KnowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name..
        /// </summary>
        public static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name....
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password wrong.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        public static string LoginFacebook {
            get {
                return ResourceManager.GetString("LoginFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user.
        /// </summary>
        public static string ModifyUser {
            get {
                return ResourceManager.GetString("ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not support access to the camera..
        /// </summary>
        public static string NoCameraSupported {
            get {
                return ResourceManager.GetString("NoCameraSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not support access to the gallery..
        /// </summary>
        public static string NoGallerySupported {
            get {
                return ResourceManager.GetString("NoGallerySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string NotAccount {
            get {
                return ResourceManager.GetString("NotAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm..
        /// </summary>
        public static string PasswordConfirmError1 {
            get {
                return ResourceManager.GetString("PasswordConfirmError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm does not match..
        /// </summary>
        public static string PasswordConfirmError2 {
            get {
                return ResourceManager.GetString("PasswordConfirmError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password confirm....
        /// </summary>
        public static string PasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password..
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone....
        /// </summary>
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone..
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to take the picture?.
        /// </summary>
        public static string PictureSource {
            get {
                return ResourceManager.GetString("PictureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizzes.
        /// </summary>
        public static string Quizzes {
            get {
                return ResourceManager.GetString("Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user has been registered ok, an email was sent to confirm the user account..
        /// </summary>
        public static string RegisterMessge {
            get {
                return ResourceManager.GetString("RegisterMessge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register self-examination.
        /// </summary>
        public static string RegisterSelfExamination {
            get {
                return ResourceManager.GetString("RegisterSelfExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a second name..
        /// </summary>
        public static string SecondNameError {
            get {
                return ResourceManager.GetString("SecondNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your second name....
        /// </summary>
        public static string SecondNamePlaceHolder {
            get {
                return ResourceManager.GetString("SecondNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Step.
        /// </summary>
        public static string SecondStep {
            get {
                return ResourceManager.GetString("SecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See maps - diagnostic centers and community support.
        /// </summary>
        public static string SeeMaps {
            get {
                return ResourceManager.GetString("SeeMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show quizzes history.
        /// </summary>
        public static string ShowQuizzesHistory {
            get {
                return ResourceManager.GetString("ShowQuizzesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take care, Examine.
        /// </summary>
        public static string TakeCare {
            get {
                return ResourceManager.GetString("TakeCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Step.
        /// </summary>
        public static string ThirdStep {
            get {
                return ResourceManager.GetString("ThirdStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together we are stronger.
        /// </summary>
        public static string Together {
            get {
                return ResourceManager.GetString("Together", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ALL.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View stadistics.
        /// </summary>
        public static string ViewStadistics {
            get {
                return ResourceManager.GetString("ViewStadistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Pink World.
        /// </summary>
        public static string WelcomePink {
            get {
                return ResourceManager.GetString("WelcomePink", resourceCulture);
            }
        }
    }
}
